name: 吾爱破解签到
 
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_request:
  schedule:
    - cron: 0 10 * * *
  watch:
    types: [started]
    
jobs:
  build:
    
    runs-on: ubuntu-lastest
    if: github.event.repository.ower.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: 安装Python依赖
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: 运行52pojie签到脚本
        run: |
          cookie='${{ secrets.COOKIE52 }}'
          SCKEY='${{ secrets.SCKEY }}'
          
          python 52pijie.py <<EOF
          ${cookie}
          %{SCKEY}
          EOF
