# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: 爱奇艺会员签到

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - name: "初始化Python"
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: "安装Python依赖"
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        
    - name: "运行 爱奇艺会员签到" 
      run: python3 iqiyi.py
      env: 
        P1: ${{ secrets.P1 }}
        P3: ${{ secrets.P3 }}
        SCKEY: ${{ secrets.SCKEY }}
