name: 爱奇艺会员签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 运行爱奇艺会员签到脚本
      run: |
        pip install requests
        sckey='${{ secrets.SCKEY }}'
        p1='${{ secrets.P1 }}'
        p3='${{ secrets.P3 }}'
        
        python3 iqiyi.py <<EOF
        ${sckey}
        ${p1}
        ${p3}
        EOF 
