name: 爱奇艺签到抽奖
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: 0 22  * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@master
      - name: 初始化Python环境
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 安装依赖并替换环境变量
        env:
          SCKEY: ${{ secrets.SCKEY }}
          P00001: ${{ secrets.P00001 }}
          P00003: ${{ secrets.P00003 }}
        run: |
          pip install -r requirements.txt
          python3 iqiyi.py
