# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: 小米运动刷步

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 安装Python依赖
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: 运行小米运动刷步脚本
      env:
        SCKEY: ${{ secrets.SCKEY }}
        USER: ${{ secrets.USER }}
        PWD: ${{ secrets.PWD }}
        STEP: ${{ secrets.STEP }}
      run: |
        python3 Mi_Sports.py 
