# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: 小米运动刷步

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
  schedule:
    - cron: 0 10 * * *
      
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - uses: actions/checkout@v2
      - name: 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: 运行Mi_Sports脚本 
        run: |
          pip install requests
          sckey='${{ secrets.SCKEY }}'
          user='${{ secrets.USER }}'
          pwd='${{ secrets.PWD }}'
          step='${{ secrets.STEP }}'
          
          python3 Mi_Sports.py <<EOF
          ${sckey}
          ${user}
          ${pwd}
          ${step}
          EOOF
