# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: 小米运动刷步

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
#  schedule:
#    - cron: 0 10 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 安装Python依赖
      run: |
        pip install -r requirements.txt
        sckey='${{ secrets.SCKEY }}'
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP }}'
        
        python3 Mi_Sports.py <<EOF
        ${sckey}
        ${user}
        ${pwd}
        ${step}
        EOF
